// book.model.ts

export interface Book {
    id?: number; // Optional if the ID is generated by the server
    title: string;
    author: string;
    genre: string;
    condition: string;
    availability: string;
  }
  